/srv/scripts/string_replace.sh binlog_format MIXED
/srv/scripts/string_replace.sh innodb_file_per_table 1
/srv/scripts/string_replace.sh slow_query_log 1
/srv/scripts/string_replace.sh slow_query_log_file /d/mysql/slow.log
/srv/scripts/string_replace.sh long_query_time 2
/srv/scripts/string_replace.sh sync_binlog 0
/srv/scripts/string_replace.sh innodb_flush_log_at_trx_commit 2
/srv/scripts/string_replace.sh innodb_flush_method O_DIRECT
/srv/scripts/string_replace.sh slave_parallel_workers 4
/srv/scripts/string_replace.sh innodb_log_file_size 512M
/srv/scripts/string_replace.sh sort_buffer_size 4M
/srv/scripts/string_replace.sh join_buffer_size 4M
/srv/scripts/string_replace.sh innodb_log_buffer_size 64M
/srv/scripts/string_replace.sh thread_cache_size 151
/srv/scripts/string_replace.sh innodb_buffer_pool_size 1G
/srv/scripts/string_replace.sh innodb_buffer_pool_instances 4
/srv/scripts/string_replace.sh max_connections 151
/srv/scripts/string_replace.sh tmp_table_size 64M
/srv/scripts/string_replace.sh max_heap_table_size 64M